# Exploratory Data Analysis of Fall-Detection Dataset

In [1]:
from utils import *
import os, re
import pandas as pd
from mat4py import loadmat

### Load dataset into a `pandas` dataframe

In [2]:
# Initialise empty dataframe
df_dataset = pd.DataFrame(columns=['subject', 'time', 'w', 'x', 'y', 'z', 'droll', 'dpitch', 'dyaw', 'ax', 'ay', 'az', 'heart', 'scenario', 'class'])

# Iterate through each subject folder
for folder in os.listdir(DATASET_FOLDER):
    current_folder = os.path.join(DATASET_FOLDER, folder)
    if("subject" in folder):
        subject = folder
        # Iterate through each class (fall or non-fall)
        for fall_class in os.listdir(current_folder):
            current_path = os.path.join(current_folder, fall_class)
            # Iterate through each file
            for file in os.listdir(current_path):
                regex_match = re.match("(.+)\\.mat", file)
                if(regex_match):
                    # Load the .mat file
                    data = loadmat(os.path.join(current_path, file))
                    data['subject'] = subject
                    data['scenario'] = regex_match.group(1)
                    data['class'] = fall_class
                    df_dataset.loc[len(df_dataset)] = data

# Add demographic data
demographic_data = {
                    "subject_01": {"age": 31, "sex": "Male" },
                    "subject_02": {"age": 21, "sex": "Female" },
                    "subject_03": {"age": 28, "sex": "Male" },
                    "subject_04": {"age": 25, "sex": "Male" },
                    "subject_05": {"age": 21, "sex": "Female" },
                    "subject_06": {"age": 28, "sex": "Male" },
                    "subject_07": {"age": 32, "sex": "Male" },
                    "subject_08": {"age": 22, "sex": "Female" },
                    "subject_09": {"age": 27, "sex": "Male" },
                    "subject_10": {"age": 25, "sex": "Male" },
                    "subject_11": {"age": 27, "sex": "Male" },
                    "subject_12": {"age": 26, "sex": "Male" },
                    "subject_13": {"age": 21, "sex": "Female" },
                    "subject_14": {"age": 21, "sex": "Female" },
                    "subject_15": {"age": 29, "sex": "Female" },
                    "subject_16": {"age": 30, "sex": "Male" },
                    "subject_17": {"age": 23, "sex": "Female" },
                    "subject_18": {"age": 28, "sex": "Male" },
                    "subject_19": {"age": 25, "sex": "Male" },
                    "subject_20": {"age": 21, "sex": "Female" },
                    "subject_21": {"age": 30, "sex": "Male" }
                }
df_dataset['age'] = df_dataset['subject'].map(lambda x: demographic_data[x]['age'] if x in demographic_data else None)
df_dataset['sex'] = df_dataset['subject'].map(lambda x: demographic_data[x]['sex'] if x in demographic_data else None)

# Reorder columns
df_dataset = df_dataset[['subject', 'age', 'sex', 'scenario', 'class', 'time', 'w', 'x', 'y', 'z', 'droll', 'dpitch', 'dyaw', 'ax', 'ay', 'az', 'heart']]

In [3]:
# Export dataframe
pickle_object(df_dataset, DATASET_FILE)

In [4]:
df_dataset.shape

(349, 17)

In [5]:
df_dataset.head()

,subject,age,sex,scenario,class,time,w,x,y,z,droll,dpitch,dyaw,ax,ay,az,heart
0,subject_12,26,Male,fall6,fall,"[[2018.0, 4.0, 25.0, 16.0, 46.0, 58.206], [201...","[[-0.62], [-0.6202], [-0.6204], [-0.6206], [-0...","[[-0.7445], [-0.7444], [-0.7442], [-0.7441], [...","[[-0.0062], [-0.0065], [-0.0067], [-0.007], [-...","[[0.2471], [0.2471], [0.2469], [0.2468], [0.24...","[[-0.1], [0.0], [0.0], [0.2], [0.5], [0.7], [0...","[[0.0], [0.0], [0.0], [-0.5], [-0.5], [-0.5], ...","[[0.5], [0.0], [0.0], [0.3], [0.3], [0.3], [0....","[[-0.004], [-0.004], [-0.001], [-0.004], [-0.0...","[[0.0], [0.0], [0.001], [0.001], [0.002], [0.0...","[[0.004], [0.006], [0.003], [-0.002], [0.001],...","[[1023], [0], [0], [0], [0], [0], [0], [0], [0..."
1,subject_12,26,Male,fall5,fall,"[[2018.0, 4.0, 25.0, 16.0, 44.0, 48.028], [201...","[[-0.9038], [-0.9038], [-0.9038], [-0.9038], [...","[[0.1272], [0.1273], [0.1273], [0.1273], [0.12...","[[0.3895], [0.3895], [0.3895], [0.3895], [0.38...","[[0.1226], [0.1226], [0.1226], [0.1227], [0.12...","[[0.0], [0.0], [-0.5], [0.0], [0.0], [0.0], [0...","[[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0....","[[0.0], [0.0], [0.3], [0.0], [0.0], [0.0], [0....","[[0.007], [0.008], [0.008], [0.009], [0.009], ...","[[0.0], [0.002], [0.003], [-0.003], [0.0], [-0...","[[-0.013], [-0.014], [-0.001], [-0.01], [-0.00...","[[1023], [1023], [1023], [1023], [1023], [1023..."
2,subject_12,26,Male,fall1,fall,"[[2018.0, 4.0, 25.0, 16.0, 25.0, 36.085], [201...","[[-0.1487], [-0.1486], [-0.1486], [-0.1486], [...","[[0.4491], [0.4491], [0.4491], [0.449], [0.449...","[[-0.013], [-0.0131], [-0.0132], [-0.0132], [-...","[[-0.8808], [-0.8809], [-0.8809], [-0.8809], [...","[[0.5], [0.5], [0.6], [0.5], [0.0], [0.0], [0....","[[0.0], [0.1], [0.0], [0.0], [0.0], [0.0], [0....","[[-0.1], [-0.1], [-0.3], [-0.1], [0.0], [0.0],...","[[-0.004], [-0.005], [-0.009], [-0.01], [-0.01...","[[0.0], [0.003], [0.0], [0.004], [0.004], [0.0...","[[-0.003], [-0.008], [-0.003], [-0.004], [-0.0...","[[0], [0], [0], [0], [0], [0], [0], [0], [0], ..."
3,subject_12,26,Male,fall2,fall,"[[2018.0, 4.0, 25.0, 16.0, 32.0, 15.167], [201...","[[-0.3838], [-0.3837], [-0.3837], [-0.3837], [...","[[0.2556], [0.2555], [0.2555], [0.2555], [0.25...","[[-0.5961], [-0.5962], [-0.5962], [-0.5962], [...","[[-0.6572], [-0.6572], [-0.6572], [-0.6572], [...","[[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0....","[[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0....","[[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0....","[[-0.007], [-0.003], [-0.006], [-0.004], [-0.0...","[[-0.001], [0.006], [-0.001], [0.002], [0.001]...","[[0.001], [-0.002], [0.0], [-0.002], [-0.003],...","[[1023], [1023], [1023], [1023], [1023], [0], ..."
4,subject_12,26,Male,fall3,fall,"[[2018.0, 4.0, 25.0, 16.0, 40.0, 17.002], [201...","[[0.0254], [0.0252], [0.0251], [0.025], [0.025...","[[0.456], [0.4562], [0.4564], [0.4566], [0.456...","[[-0.0176], [-0.0177], [-0.0177], [-0.0176], [...","[[0.8893], [0.8892], [0.8891], [0.8891], [0.88...","[[0.2], [0.4], [0.6], [0.5], [0.0], [0.0], [-0...","[[1.3], [1.3], [0.9], [0.5], [0.0], [0.0], [-0...","[[-0.1], [-0.1], [-0.2], [-0.1], [0.0], [0.0],...","[[0.007], [0.005], [0.005], [0.003], [0.003], ...","[[-0.002], [-0.003], [-0.002], [-0.003], [-0.0...","[[-0.003], [-0.005], [-0.009], [-0.007], [-0.0...","[[0], [0], [1023], [1023], [1023], [1023], [10..."